###########################################################
#                                                         #
#    Hall motion sensor -> OFF                            #
#                                                         #
###########################################################
- alias: motion_hall_on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hall
      to: 'on'

  action:
    - service: timer.cancel
      data:
        entity_id: timer.dressing_room_timer
    - service: light.turn_on
      data:
        brightness_pct: 100
        entity_id: light.deconz_dressing_room_fitting


###########################################################
#                                                         #
#    Hall motion sensor -> OFF                            #
#                                                         #
###########################################################
- alias: motion_hall_off
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hall
      to: 'off'

  action:
    - service: timer.cancel
      data:
        entity_id: timer.dressing_room_timer
    - service: timer.start
      data:
        entity_id: timer.dressing_room_timer
        duration: '00:05:00'


###########################################################
#                                                         #
#    Dressing room timer -> FINISHED                      #
#                                                         #
###########################################################
- alias: dressing_room_timer_finished
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.dressing_room_timer

  action:
    - service: light.turn_off
      data:
        entity_id: light.deconz_dressing_room_fitting
