###########################################################
#                                                         #
#    (DAY)                                                #
#    Hallway bathroom motion sensor -> ON                 #
#    Front door (inner) opening -> ON                     #
#                                                         #
###########################################################
- alias: motion_hallway_bathroom_or_opening_front_door_inner_on_day
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway_bathroom, binary_sensor.opening_front_door_inner
      to: 'on'

  condition:
    - condition: time
      after: 06:30
      before: '21:00'

  action:
    - service: timer.cancel
      data:
        entity_id: timer.hall_hallway_bathroom_timer
    - service: light.turn_on
      data:
        brightness_pct: 100
        entity_id:
          - light.deconz_hallway_bathroom_ceiling_fittings
          - light.deconz_hall_ceiling_fittings


###########################################################
#                                                         #
#    (DAY)                                                #
#    Hallway bathroom motion sensor -> OFF                #
#    Front door (inner) opening -> OFF                    #
#                                                         #
###########################################################
- alias: motion_hallway_bathroom_or_opening_front_door_inner_off_day
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway_bathroom, binary_sensor.opening_front_door_inner
      to: 'off'

  condition:
    - condition: time
      after: 06:30
      before: '21:00'

  action:
    - service: timer.cancel
      data:
        entity_id: timer.hall_hallway_bathroom_timer
    - service: timer.start
      data:
        entity_id: timer.hall_hallway_bathroom_timer
        duration: '00:05:00'


###########################################################
#                                                         #
#    (NIGHT)                                              #
#    Hallway bathroom motion sensor -> ON                 #
#    Front door (inner) opening -> ON                     #
#                                                         #
###########################################################
- alias: motion_hallway_bathroom_or_opening_front_door_inner_on_night
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway_bathroom, binary_sensor.opening_front_door_inner
      to: 'on'

  condition:
    - condition: time
      after: '21:00'
      before: 06:30

  action:
    - service: timer.cancel
      data:
        entity_id: timer.hall_hallway_bathroom_timer
    - service: light.turn_on
      data:
        brightness_pct: 10
        entity_id:
          - light.deconz_hallway_bathroom_ceiling_fittings
          - light.deconz_hall_ceiling_fittings


###########################################################
#                                                         #
#    (NIGHT)                                              #
#    Hallway bathroom motion sensor -> OFF                #
#    Front door (inner) opening -> OFF                    #
#                                                         #
###########################################################
- alias: motion_hallway_bathroom_or_opening_front_door_inner_off_night
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway_bathroom, binary_sensor.opening_front_door_inner
      to: 'off'

  condition:
    - condition: time
      after: '21:00'
      before: 06:30

  action:
    - service: timer.cancel
      data:
        entity_id: timer.hall_hallway_bathroom_timer
    - service: timer.start
      data:
        entity_id: timer.hall_hallway_bathroom_timer
        duration: '00:01:00'


###########################################################
#                                                         #
#    Hall/Hallway bathroom timer -> FINISHED              #
#                                                         #
###########################################################
- alias: hall_hallway_bathroom_timer_finished
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.hall_hallway_bathroom_timer

  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.deconz_hallway_bathroom_ceiling_fittings
          - light.deconz_hall_ceiling_fittings
