###########################################################
#                                                         #
#     (DAY)                                               #
#     Kitchen motion sensor -> ON                         #
#                                                         #
###########################################################
- alias: motion_kitchen_on_day
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kitchen
      to: 'on'

  condition:
    - condition: time
      after: 06:30
      before: '22:30'

  action:
    - service: timer.cancel
      data:
        entity_id: timer.kitchen_timer
    - service: light.turn_on
      data:
        brightness_pct: 70
        entity_id: light.deconz_kitchen_ceiling_fitting


###########################################################
#                                                         #
#     (DAY)                                               #
#     Kitchen motion sensor -> OFF                        #
#                                                         #
###########################################################
- alias: motion_kitchen_off_day
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kitchen
      to: 'off'

  condition:
    - condition: time
      after: 06:30
      before: '22:30'

  action:
    - service: timer.cancel
      data:
        entity_id: timer.kitchen_timer
    - service: timer.start
      data:
        entity_id: timer.kitchen_timer
        duration: '00:05:00'


###########################################################
#                                                         #
#     (NIGHT)                                             #
#     Kitchen motion sensor -> ON                         #
#                                                         #
###########################################################
- alias: motion_kitchen_on_night
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kitchen
      to: 'on'

  condition:
    - condition: time
      after: '22:30'
      before: 06:30

  action:
    - service: timer.cancel
      data:
        entity_id: timer.kitchen_timer
    - service: light.turn_on
      data:
        brightness_pct: 10
        entity_id: light.deconz_kitchen_ceiling_fitting


###########################################################
#                                                         #
#     (NIGHT)                                             #
#     Kitchen motion sensor -> OFF                        #
#                                                         #
###########################################################
- alias: motion_kitchen_off_night
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_kitchen
      to: 'off'

  condition:
    - condition: time
      after: '22:30'
      before: 06:30

  action:
    - service: timer.cancel
      data:
        entity_id: timer.kitchen_timer
    - service: timer.start
      data:
        entity_id: timer.kitchen_timer
        duration: '00:01:00'


###########################################################
#                                                         #
#    Kitchen timer -> FINISHED                            #
#                                                         #
###########################################################
- alias: kitchen_timer_finished
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.kitchen_timer

  action:
    - service: light.turn_off
      data:
        entity_id: light.deconz_kitchen_ceiling_fitting
