###########################################################
#                                                         #
#     (DAY)                                               #
#     Hallway master bedroom motion sensor -> ON          #
#                                                         #
###########################################################
- alias: motion_hallway_master_bedroom_on_day
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway_master_bedroom
      to: 'on'

  condition:
    - condition: time
      after: 07:30
      before: '21:00'

  action:
    - service: timer.cancel
      data:
        entity_id: timer.hallway_master_bedroom_timer
    - service: light.turn_on
      data:
        entity_id: light.deconz_hallway_master_bedroom_ceiling_fitting
        brightness_pct: 100


###########################################################
#                                                         #
#     (DAY)                                               #
#     Hallway master bedroom motion sensor -> OFF         #
#                                                         #
###########################################################
- alias: motion_hallway_master_bedroom_off_day
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway_master_bedroom
      to: 'off'

  condition:
    - condition: time
      after: 07:30
      before: '21:00'

  action:
    - service: timer.cancel
      data:
        entity_id: timer.hallway_master_bedroom_timer
    - service: timer.start
      data:
        entity_id: timer.hallway_master_bedroom_timer
        duration: '00:02:00'


###########################################################
#                                                         #
#     (NIGHT)                                             #
#     Hallway master bedroom motion sensor -> ON          #
#                                                         #
###########################################################
- alias: motion_hallway_master_bedroom_on_night
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway_master_bedroom
      to: 'on'

  condition:
    - condition: time
      after: '21:00'
      before: 07:30

  action:
    - service: timer.cancel
      data:
        entity_id: timer.hallway_master_bedroom_timer
    - service: light.turn_on
      data:
        entity_id: light.deconz_hallway_master_bedroom_ceiling_fitting
        brightness_pct: 10


###########################################################
#                                                         #
#     (NIGHT)                                             #
#     Hallway master bedroom motion sensor -> OFF         #
#                                                         #
###########################################################
- alias: motion_hallway_master_bedroom_off_night
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway_master_bedroom
      to: 'off'

  condition:
    - condition: time
      after: '21:00'
      before: 07:30

  action:
    - service: timer.cancel
      data:
        entity_id: timer.hallway_master_bedroom_timer
    - service: timer.start
      data:
        entity_id: timer.hallway_master_bedroom_timer
        duration: '00:01:00'


###########################################################
#                                                         #
#    Master bedroom timer -> FINISHED                     #
#                                                         #
###########################################################
- alias: hallway_master_bedroom_timer_finished
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.hallway_master_bedroom_timer

  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.deconz_hallway_master_bedroom_ceiling_fitting
