- alias: Hallway master bedroom lights on - day - motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway_master_bedroom
      to: 'on'

  condition:
    - condition: time
      after: 07:30
      before: '21:00'

  action:
    - service: timer.cancel
      data:
        entity_id: timer.hallway_master_bedroom_timer
    - service: light.turn_on
      data:
        entity_id: light.deconz_hallway_master_bedroom_ceiling_fitting
        brightness_pct: 100
    - service: timer.start
      data:
        entity_id: timer.hallway_master_bedroom_timer
        duration: '00:02:00'

- alias: Hallway master bedroom lights on - nigh - motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway_master_bedroom
      to: 'on'

  condition:
    - condition: time
      after: '21:00'
      before: 07:30

  action:
    - service: timer.cancel
      data:
        entity_id: timer.hallway_master_bedroom_timer
    - service: light.turn_on
      data:
        entity_id: light.deconz_hallway_master_bedroom_ceiling_fitting
        brightness_pct: 10
    - service: timer.start
      data:
        entity_id: timer.hallway_master_bedroom_timer
        duration: '00:01:00'

- alias: Hallway master bedroom timer finished
  trigger:
    platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.hallway_master_bedroom_timer

  action:
    - service: light.turn_off
      data:
        entity_id:
          - light.deconz_hallway_master_bedroom_ceiling_fitting
