###########################################################
#                                                         #
#    Mira button bed short press                          #
#                                                         #
###########################################################
- alias: button_bed_mira_short_press

  trigger:
    platform: event
    event_type: deconz_event
    event_data:
      id: button_bed_mira
      event: 1002

  action:
    - service_template: >
        {% if is_state('light.mira_window', 'off') %}
          homeassistant.turn_on
        {% else %}
          homeassistant.turn_off
        {% endif %}
      data:
        entity_id:
          - light.mira_window
          - group.mira_wall_lights
