- alias: Turn off all lights work days
  trigger:
    platform: time
    at: '22:30:00'

  condition:
    condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - sun

  action:
    - service: light.turn_off
      data:
        entity_id: all

- alias: Turn off all lights weekend
  trigger:
    platform: time
    at: '23:30:00'

  condition:
    condition: time
    weekday:
    - fri
    - sat

  action:
    - service: light.turn_off
      data:
        entity_id: all
