- alias: Set correct source when casting
  trigger:
  - platform: state
    entity_id: media_player.vardagsrum
    to: playing

  action:
    - service: media_player.turn_on
      data:
        entity_id: media_player.marantz
    - service: media_player.select_source
      data:
        entity_id: media_player.marantz
        source: CAST
